/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StrategyAnalyticsRouteImport } from './routes/strategy-analytics'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as BacktestingRouteImport } from './routes/backtesting'
import { Route as IndexRouteImport } from './routes/index'

const StrategyAnalyticsRoute = StrategyAnalyticsRouteImport.update({
  id: '/strategy-analytics',
  path: '/strategy-analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const BacktestingRoute = BacktestingRouteImport.update({
  id: '/backtesting',
  path: '/backtesting',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/backtesting': typeof BacktestingRoute
  '/settings': typeof SettingsRoute
  '/strategy-analytics': typeof StrategyAnalyticsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/backtesting': typeof BacktestingRoute
  '/settings': typeof SettingsRoute
  '/strategy-analytics': typeof StrategyAnalyticsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/backtesting': typeof BacktestingRoute
  '/settings': typeof SettingsRoute
  '/strategy-analytics': typeof StrategyAnalyticsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/backtesting' | '/settings' | '/strategy-analytics'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/backtesting' | '/settings' | '/strategy-analytics'
  id: '__root__' | '/' | '/backtesting' | '/settings' | '/strategy-analytics'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BacktestingRoute: typeof BacktestingRoute
  SettingsRoute: typeof SettingsRoute
  StrategyAnalyticsRoute: typeof StrategyAnalyticsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/strategy-analytics': {
      id: '/strategy-analytics'
      path: '/strategy-analytics'
      fullPath: '/strategy-analytics'
      preLoaderRoute: typeof StrategyAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backtesting': {
      id: '/backtesting'
      path: '/backtesting'
      fullPath: '/backtesting'
      preLoaderRoute: typeof BacktestingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BacktestingRoute: BacktestingRoute,
  SettingsRoute: SettingsRoute,
  StrategyAnalyticsRoute: StrategyAnalyticsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
